### 파일 임시저장
POST {{host}}/common/temp/file
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token-sdm}}

--boundary
Content-Disposition: form-data; name="file"; filename="test-img.jpg"

< ../asset/test.jpg

### 이미지 임시저장
POST {{host}}/common/temp/image?width=200&height=100
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token-sdm}}

--boundary
Content-Disposition: form-data; name="file"; filename="test-img.jpg"

< ../asset/test.jpg