### [로컬] 내 클럽 조회
GET http://localhost:8080/clubs/my
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### [개발] 내 클럽 조회
GET http://ec2-52-78-18-217.ap-northeast-2.compute.amazonaws.com/api/clubs/my
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}


### [개발] 내 클럽 가입
POST {{host}} /clubs/6174/users
Accept: application/json
Authorization: Bearer {{token-sdm}}


### 모임 삭제
DELETE {{host}}/clubs/6386
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-jun}}