###  내 모임 게시글 댓글 조회
GET  {{host}}/club/6174/board/7/comment
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-dong}}

### 내 모임 게시글 댓글 등록
POST {{host}}/club/6327/board/7/comment
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "content" : "테스트 댓글"
}

### 내 모임 게시글 대댓글 등록
POST {{host}}/club/6327/board/7/comment?parentCommentSeq=36
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "content" : "테스트 댓글"
}

### 내 모임 게시글 댓글 조회
GET {{host}}/club/6174/board/7/comment?page=0&size=20
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### 내 모임 게시글 대댓글 조회
GET {{host}}/club/6174/board/7/comment/36
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### 내 모임 게시글 댓글 삭제
DELETE {{host}}/club/6212/board/60/comment/107
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDM5NTI4NTk3Iiwic3ViIjoiMTQzOTUyODU5NyIsImlhdCI6MTYxODc0MTU3MCwiZXhwIjoxNjE5MzQ2MzcwfQ.3eAa3y3hgIhQQAfOiq6AW_Qt_Seuf4YcnwBPVNfexpc
