### 내 모임 게시판 등록
POST {{host}}/clubs/6174/board
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "title"    : "테스트 제목",
  "content"  : "테스트 글"  ,
  "category" : "NORMAL"   ,
  "imgUrl"   : [{
    "absolutePath" : "https://super-invention-static.s3.ap-northeast-2.amazonaws.com/temp/img/20201212112310-c234aede-b227-4fd3-a02c-13a86624c7ef-test.png",
    "filePath"     : "/temp/img/20201212112310-c234aede-b227-4fd3-a02c-13a86624c7ef-test.png",
    "fileName"     : "20201212112310-c234aede-b227-4fd3-a02c-13a86624c7ef-test.png"
  }]
}

### 모임 게시판 조회
GET {{host}}/clubs/6174/board?category=NOTICE
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}
GlobalAdviceController

### 모임 게시판 단일 조회
GET {{host}}/clubs/6174/board/2
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}