### [로컬] 내 클럽 사진첩 좋아요 등록
POST {{host}}/club/6174/album/6451/like
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### [로컬] 내 클럽 사진첩 좋아요 등록
DELETE {{host}}/club/6174/album/6451/like
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}