###  내 클럽 사진첩 댓글 조회
GET  {{host}}/club/6174/album/6943/comment
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-dong}}

### 내 모임 사진첩 댓글 등록
POST {{host}}/club/6174/album/6943/comment
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "content" : "테스트 댓글"
}

### 내 모임 사진첩 대댓글 조회
GET {{host}}/club/6174/album/6943/comment/6887
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### 내 모임 사진첩 대댓글 등록
POST {{host}}/club/6174/album/6943/comment/6887
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "content" : "테스트 대댓글"
}