### [로컬] 내 클럽 사진첩 좋아요 등록
POST http://localhost:8080/club/6174/album/6451/like
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDEyMzc1MzA5Iiwic3ViIjoiMTQxMjM3NTMwOSIsImlhdCI6MTYwNzUyMTI2OSwiZXhwIjoxNjM5MDU3MjY5fQ.89WmDakxELDdxVSV5eN7jvSuY75E_OQ8IXy8kb5iVN0

### [로컬] 내 클럽 사진첩 좋아요 등록
DELETE http://localhost:8080/club/6174/album/6451/like
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDEyMzc1MzA5Iiwic3ViIjoiMTQxMjM3NTMwOSIsImlhdCI6MTYwNzUyMTI2OSwiZXhwIjoxNjM5MDU3MjY5fQ.89WmDakxELDdxVSV5eN7jvSuY75E_OQ8IXy8kb5iVN0