### 내 클럽 사진첩 등록
POST {{host}}/club/6174/album
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

{
  "title": "1234",
  "file_name": "20201212112310-c234aede-b227-4fd3-a02c-13a86624c7ef-test.png",
  "imgUrl": "https://super-invention-static.s3.ap-northeast-2.amazonaws.com/temp/img/20201212112310-c234aede-b227-4fd3-a02c-13a86624c7ef-test.png"
}

### 모임 사진첩  사진첩 조회
GET {{host}}/club/6327/album
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### 모임 사진첩 단일 조회
GET {{host}}/club/6327/album/6652
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}