### 최종 회원 가입 여부 조회
GET {{host}} /users/check-already-register
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-tester}}

### 유저 백도어 조회
GET {{host}}/users/door/꽑꽑이
Content-Type: application/json;charset=UTF-8
Accept: application/json



### 유저리스트 백도어 조회
GET {{host}}/users/door
Content-Type: application/json;charset=UTF-8
Accept: application/json

### 유저 앱토큰 조회
GET {{host}}/users/door-seq/8981
Content-Type: application/json;charset=UTF-8
Accept: application/json

### 카카오 토큰 조회
GET https://kapi.kakao.com/v1/user/access_token_info HTTP/1.1
Authorization: Bearer BoXgGmmlQRziyEx8BZdtwD463IQHK
Content-type: application/x-www-form-urlencoded;charset=utf-8

### 카카오 유저 정보
GET {{host}}/users/kakao-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNDEyMzc1MzA5Iiwic3ViIjoiMTQxMjM3NTMwOSIsImlhdCI6MTYxMTQ4NTEwOCwiZXhwIjoxNjQzMDIxMTA4fQ.gJg2APZdNtewO_OIfkAhbLB0ZJzBYrTZUjR72JvzXqI

### 카카오 유저 정보
GET {{host}}/users/kakao-profile
Authorization: Bearer {{token-jun}}


### 카카오 토큰 저장
POST {{host}}/users/saveKakaoToken
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-jun}}

{
"access_token": "PV9R2cX7CDkL38yYijtgaeOtap3FV8d471Xp1Qo9cuoAAAF3etymEA",
"expireds_in": 21599,
"refresh_token": "iSoul2MdfKUFqtA1q-J2a_84-6NJw-EYrf1r1wo9cuoAAAF3etymDw",
"refresh_token_expires_in": 5183999
}

### 회원 탈퇴
DELETE {{host}}/users/withdraw
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-tester}}

### 내 정보
GET {{host}}/users/profile
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-tester}}