### 최종 회원 가입 여부 조회
GET {{host}} /users/check-already-register
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{token-sdm}}

### [로컬] 유저 백도어 조회
GET http://localhost:8080/users/door/꽑꽑이
Content-Type: application/json;charset=UTF-8
Accept: application/json



### [로컬] 유저리스트 백도어 조회
GET http://localhost:8080/users/door
Content-Type: application/json;charset=UTF-8
Accept: application/json